"""
Inject expert explanations into questions.json for each question.
Explanations focus on WHY the correct answer is right and why others are wrong.
"""

import json

EXPLANATIONS = {
    "1": "Option D is correct because using separate backend pools behind a single load balancer lets you route traffic to either API version using path-based rules, while keeping the same SSL certificate and DNS record. A new load balancer (A) would require new DNS/SSL. Reconfiguring clients (B) breaks the requirement for the same endpoint. Forwarding at the API layer (C) creates coupling and a single point of failure.",
    "2": "BigQuery (A) is designed for petabyte-scale analytical workloads and natively supports SQL. It is serverless, always available, and highly cost-effective for analytical queries on large datasets. Cloud SQL (B) is a relational transactional database not optimized for petabyte scale. Cloud Storage (C) stores flat files without SQL capability. Cloud Datastore (D) is a NoSQL document database, not a SQL query engine.",
    "3": "C, D, and E are the recommended migration practices. Instrumenting with Stackdriver (C) ensures observability. Using an automation framework for infrastructure (D) enables repeatable provisioning. Deploying CI with automated tests in staging (E) catches regressions early. Porting to App Engine (A) is optional and not a general best practice. Integrating Dataflow (B) is unrelated to migration. Migrating to NoSQL (F) is a data model decision, not a migration best practice.",
    "4": "App Engine scales by running multiple instances, and instance variables are local to each instance (A). If a user's session state is stored in a local variable, different requests may hit different instances and see different state. The session needs to be stored in a shared backend like Datastore or Memcache to be consistent.",
    "5": "The best approach (C) is to first understand the team's specific requirements, then evaluate tools that meet them. Sending resources (B) without understanding needs is not helpful. Upgrading the current tool (D) assumes it can be fixed without evaluation. Directing them straight to Stackdriver (A) skips requirements gathering.",
    "6": "Blue/green deployment (A) allows instant rollback by switching traffic between two identical environments. Canary releases in QA (B) catch issues on a subset of production users before full rollout. Fragmenting into microservices (C) reduces coupling but doesn't directly reduce rollbacks. Removing relational databases (D, E) is unrelated to deployment reliability.",
    "7": "Using --no-auto-delete on persistent disks and stopping the VM (A) preserves state without destroying the disk. BigQuery billing export with labels (D) provides cost visibility by associating VM usage to teams. Auto-deleting disks (B) would destroy state. CPU labels alone (C) don't provide cost allocation. Snapshots (E, F) add cost and complexity unnecessarily.",
    "8": "NoSQL (B) is best for IoT sensor data because it handles high-throughput writes, flexible schemas, and scales horizontally. The semi-structured sensor data plus account/location joins are a good fit. Flat files (A) don't support queries. Relational (C) struggles with the high write throughput and schema flexibility needed. Blobstore (D) is for large binary objects, not structured sensor data.",
    "9": "Health checks need firewall rules to reach instances (C). If the load balancer cannot reach instances on the health check port, it marks them unhealthy and terminates them. Firewall rules for public traffic (A) are unrelated to health checks. Public IPs (B) are unnecessary since load balancers can reach private IPs. Tagging instances with the load balancer name (D) is not a valid configuration.",
    "10": "BigQuery requires the VM to have the BigQuery OAuth scope enabled (B). Even if the API client is installed, it cannot access BigQuery without the correct access scope on the VM. Installing the API library (A) is needed but not sufficient if the scope is missing. A service account (C) works but is more complex and not the simplest fix. The bq gcloud component (D) is a CLI tool, not an API fix.",
    "11": "SAML 2.0 federation (B) lets users authenticate against their existing corporate IdP without changing passwords, which minimizes disruption and satisfies strict password storage requirements (passwords stay on-premises). G Suite Password Sync (A) replicates passwords to Google, violating the storage requirement. Cloud Directory Sync (C) provisions user accounts but not authentication. Asking users to set matching passwords (D) is insecure.",
    "12": "Cloud Dataflow (B) is a fully managed, serverless service that natively handles both batch and streaming pipelines using the Apache Beam model. Cloud Dataproc (A) runs managed Hadoop/Spark and requires more configuration for streaming. Container Engine + Bigtable (C) or Compute Engine + BigQuery (D) require extensive custom code.",
    "13": "Rolling back immediately (C) restores service while you safely investigate the problem in a non-production environment using Stackdriver Trace and Logging. Pushing the fix at a quiet time (D) still leaves users with slow load times during investigation. Opening a support ticket (B) escalates unnecessarily and delays resolution. Working with the ISP (A) is unrelated to an application-level regression.",
    "14": "You can resize a persistent disk online (while it's mounted) and then run resize2fs on Linux to expand the filesystem without any downtime (A). Shutting down the VM (B) causes downtime. fdisk (C) is for partition tables, not filesystem resize. Creating a new disk (D) requires data migration. Snapshot and restore (E) also causes downtime.",
    "15": "Tokenization (A) replaces actual card data with a meaningless token, so only the tokenizer service is in PCI scope—the rest of your architecture handles only tokens. Separate projects (B) and subnetworks (C) still handle raw card data and don't reduce PCI scope. Labeling VMs (D) only aids auditing, not scope reduction. BigQuery export (E) with ACLs is for audit access, not scope reduction.",
    "16": "Cloud Bigtable (B) is designed for high-throughput, low-latency time-series data at massive scale, handling millions of writes per second. Cloud SQL (A) would be overwhelmed at 8,500 clicks/second. Cloud Storage (C) is for object storage, not real-time ingest. Cloud Datastore (D) is a document database with lower throughput limits.",
    "17": "A lifecycle management rule in JSON pushed with gsutil (B) is the Google-recommended declarative way to delete objects older than 90 days. XML format (A) is not supported by gsutil for lifecycle rules. Cron scripts using gsutil ls (C, D) are operational overhead, not managed lifecycle policies, and gsutil ls -lr is not a valid flag combination.",
    "18": "Cloud Dataproc (B) is a managed Hadoop and Spark service that lets you run existing Spark jobs with minimal code changes, just by changing the cluster endpoint. Cloud Dataflow (A) requires rewriting pipelines in Apache Beam. Compute Engine (C) and Kubernetes Engine (D) require full infrastructure management.",
    "19": "SSD persistent disk I/O is proportional to disk size—resizing from 80 GB to 500 GB significantly increases IOPS, which is the bottleneck for a write-intensive import/normalization database (C). Adding memory (A) helps for buffer cache but the I/O limit is the real bottleneck. Switching to PostgreSQL (B) doesn't change the underlying storage. Migrating to BigQuery (D) is a different architecture for analytics, not transactional normalization.",
    "20": "Bigtable (C) is optimized for time-series data with high write throughput and low latency per row, making it ideal for 500,000 reads/writes per second from sensors. BigQuery (A) is for analytical batch queries, not real-time sensor ingest. Cloud SQL (B) can't handle the write rate. Cloud Storage (D) is object storage.",
    "21": "Replaying captured real user input (A) is the most realistic test because it reflects actual behavior. Terminating resources in one zone simultaneously tests multi-zone resilience. Synthetic input (B) may not reflect real patterns. Gradual exposure (C) is good for progressive rollout but not load testing. Pre-provisioning 200% (D) doesn't test autoscale behavior.",
    "22": "Using Alpine Linux (C) dramatically reduces the base image size. Copying source code after installing dependencies (E) allows Docker to cache the dependency layers, so code-only changes don't re-run pip install. Removing Python after pip (A) would break the app. Removing dependencies (B) breaks the app. Larger node pools (D) don't affect image build time.",
    "23": "Deploying to a small subset of users (D) (canary deployment) exposes real production load patterns that may not be reproducible in staging, surfaces issues early, and limits blast radius. Deploying fewer (A) or smaller (B) changes reduces risk but doesn't address the staging/production environment gap. Increasing staging load (C) helps but still may not match real production behavior.",
    "24": "Stackdriver Trace (D) instruments requests across microservices, showing a breakdown of latency at each service hop. This pinpoints which service is slow for the long-tail requests. Timeouts (A) fail requests faster but don't diagnose the root cause. Custom metrics (B) measure aggregate behavior, not per-request traces. Stackdriver Monitoring (C) shows infrastructure metrics, not distributed request traces.",
    "25": "Scheduled failover drills (D) validate that the promotion process works correctly and within the expected RTO before an actual outage. A replica that has never been promoted in practice may have misconfigured automation. A different database (A) doesn't fix the promotion bug. Larger instances (B) prevent crashes but don't fix the failover process. More snapshots (C) are for recovery, not failover promotion.",
    "26": "Exporting Stackdriver monitoring data to Cloud Storage (D) provides durable, low-cost long-term retention (5 years) that's accessible for legal discovery. Granting the security team direct access to logs (A) doesn't ensure long-term retention. Default Stackdriver retention (C) is only 30 days. BigQuery (B) works for analysis but is more expensive for 5-year raw log storage.",
    "27": "Google Cloud Dedicated Interconnect (A) provides a private, high-bandwidth (10–100 Gbps) connection directly to Google's network, suitable for a 4 TB database with large frequent updates. Cloud VPN (B) travels over the public internet and has limited throughput. A NAT/TLS gateway (C) adds complexity without addressing bandwidth. A Compute Engine VPN server (D) is more fragile and lower-bandwidth than Dedicated Interconnect.",
    "28": "Exporting IAM policy change logs to BigQuery and using ACLs/views (B) lets auditors run structured queries on exactly the data they need without access to other logs. Custom Stackdriver alerts (A) are real-time notifications, not historical audit reports. Cloud Functions to Cloud SQL (C) adds unnecessary complexity. GCS log export (D) provides raw logs without query capability.",
    "29": "A secret management system (C) like Cloud Secret Manager stores credentials encrypted at rest, with fine-grained access control and audit logging. Credentials in source code (A) are exposed in version control. Environment variables (B) are accessible to all processes and may be logged. Config files with ACLs (D) are harder to manage at scale across 30 microservices.",
    "30": "Unfamiliarity with Cloud Deployment Manager (C) means engineers will need training, slowing initial adoption. It only supports Google Cloud resources (F), meaning any hybrid or multi-cloud workflows would require another tool. Python syntax (A) is a minor learning curve, not a business risk. API deprecation (B) is a general GCP concern, not specific to Deployment Manager. The service account requirement (D) is standard practice. Accidental deletes (E) are a risk for any IaC tool.",
    "31": "GKE satisfies open-source portability and dynamic scaling. Jenkins provides CI/CD for continuous delivery. Helm provides dynamic templating for deployments and URL-based routing through Kubernetes Ingress. This combination satisfies all six requirements. Options without Jenkins (B, C) miss continuous delivery. Options without Helm (D) miss dynamic templates and flexible routing.",
    "32": "Preemptible VMs receive a shutdown signal 30 seconds before termination. The correct way to handle this is a shutdown script registered in instance metadata using the shutdown-script key (C). The metadata service triggers this script on preemption. Scripts in Linux rc directories (A) work for normal reboots but not cloud preemption. xinetd services (B, D) are not the right mechanism.",
    "33": "Network tags combined with firewall rules (D) are the GCP-native way to control traffic flow between tiers. You tag each tier and create rules that allow web→API and API→database traffic. Subnetworks (A) provide network segmentation but don't control intra-VPC traffic by themselves. Software firewalls (B) add complexity and single points of failure. Routes (C) control packet forwarding at layer 3, not application-layer access control.",
    "34": "Stackdriver Logging (A) captures kernel module logs and application errors. The serial console (C) shows kernel boot and kernel panic messages that aren't in regular logs. The GCE Activity log (D) shows live migration events, which are important if the kernel module is incompatible with live migration. Read GCE Activity log (B) is vague; it should be the instance activity log for specific events. Exporting to a local server (F) is complex and slow. Adjusting Stackdriver timeline (E) shows metrics but not kernel-level crash data.",
    "35": "Loading logs into BigQuery (A) enables SQL analytics at scale. Uploading to Cloud Storage (E) provides cheap durable long-term storage for disaster recovery. These two together satisfy both requirements. Cloud SQL (B) can't handle 100 TB. Stackdriver (C) is for live monitoring, not archival. Bigtable (D) is for high-throughput ingest, not log archival and analytics.",
    "36": "Reverting the source code change and rerunning the pipeline (B) is the cleanest approach—let the automated pipeline deploy a known-good version, keeping the deployment process consistent. Logging into servers to fix code locally (A, C) breaks infrastructure-as-code discipline. Changing the instance group template and deleting instances (D) achieves the same result manually but kills all instances at once.",
    "37": "A single Organization with Folders for each department (C) allows centralized governance at the Organization level while giving each department's folder its own IAM policies. Multiple organizations (A, B) prevent centralized control. A single project per department with a central owner (D) doesn't provide IAM isolation between departments.",
    "38": "A missing JAR file is the most common cause of a deployment failure with this error pattern in App Engine. Uploading missing JARs and redeploying (A) resolves it. Signing JARs (B) is for Applets and is irrelevant here. Recompiling with a different hash (C) is not related to this error.",
    "39": "PKI with asymmetric encryption (C) lets a user sign a message with their private key. Anyone with the public key can verify authenticity, ensuring the message could only have been signed by that user. Client-side tagging (A) is easily spoofed. Shared-key encryption (B) can't prove authorship since anyone with the shared key can encrypt. SSL (D) protects transport, not message-level authorship.",
    "40": "Dedicated Interconnect (B) provides a high-bandwidth, low-latency private connection that eliminates the packet loss and latency seen over Cloud VPN, which traverses the public internet. Switching to UDP (A) would make it worse since replication relies on TCP reliability. Cloud SQL restore (C) is a different approach to disaster recovery, not replication. Adding VPN connections (D) doesn't reduce inherent internet latency/loss. Pub/Sub (E) is for event streaming, not database replication.",
    "41": "The Cloud Data Loss Prevention (DLP) API (C) is specifically designed to identify and de-identify PII and payment card data, supporting tokenization, masking, and redaction. SHA256 hashing (A) is irreversible and destroys data utility. Elliptic curve encryption (B) encrypts all data without de-identification. Regex (D) misses complex patterns and has poor recall for detection.",
}

def main():
    with open('questions.json', encoding='utf-8') as f:
        questions = json.load(f)

    injected = 0
    for q in questions:
        num = str(q.get('number', ''))
        if num in EXPLANATIONS:
            q['explanation'] = EXPLANATIONS[num]
            injected += 1

    with open('questions.json', 'w', encoding='utf-8') as f:
        json.dump(questions, f, indent=4, ensure_ascii=False)

    print(f"Injected explanations into {injected} questions (out of {len(questions)} total).")
    print(f"Remaining {len(questions) - injected} questions have the default 'Verified' explanation.")

if __name__ == '__main__':
    main()
